### ISSUE TITLE
Steps in readme make failing tests

### ISSUE THREAD

**Issue by thekevinbrown** [infinitex-tech/infeos#6]
**Version of infeos**
0.1.33

**Describe the bug**
I ran through the steps in the readme, and when I run `infeos test` I get:

```
$ infeos test 


  Planet Contract Tests
    1) should create a new planet

  Star Contract Tests
    2) should create a new star
    3) should add a new planet to existing star
    4) should throw when adding a non-existing planet to a star


  0 passing (16ms)
  4 failing

  1) Planet Contract Tests
       should create a new planet:
     TypeError: universeContractInstance.createstar is not a function
      at Context.it (test/PlanetTests.js:43:40)

  2) Star Contract Tests
       should create a new star:
     TypeError: universeContractInstance.createstar is not a function
      at Context.it (test/StarTests.js:43:40)

  3) Star Contract Tests
       should add a new planet to existing star:
     TypeError: universeContractInstance.createstar is not a function
      at Context.it (test/StarTests.js:62:40)

  4) Star Contract Tests
       should throw when adding a non-existing planet to a star:
     TypeError: universeContractInstance.createstar is not a function
      at Context.it (test/StarTests.js:89:40)
```

**To Reproduce**
Follow the steps in the readme until the end.

**Expected behavior**
I expected the tests to pass.

**Desktop (please complete the following information):**
 - OS: macOS X Mojave
 - Version 10.14.2

**Comment by Gammanik** [comment]
yes this is a problem. adding [universe.abi](https://gist.github.com/DimitarSD/9b3af2a3312b78fe4c0826018e7346ce) in the src & build folders is solving it.
They just didn't mention you need to do it
